# Generated by Django 4.0.4 on 2022-05-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hub', models.CharField(max_length=30, null=True)),
                ('features', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sirens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=30, null=True)),
                ('typeSiren', models.CharField(max_length=200, null=True)),
                ('batteryLife', models.CharField(max_length=30, null=True)),
                ('alarmLife', models.CharField(max_length=30, null=True)),
                ('hubId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_api.hubs')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=30, null=True)),
                ('sensitiveElement', models.CharField(max_length=30, null=True)),
                ('typeSensor', models.CharField(max_length=200, null=True)),
                ('batteryLife', models.CharField(max_length=30, null=True)),
                ('hubId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_api.hubs')),
            ],
        ),
        migrations.AddField(
            model_name='hubs',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_api.user'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_api.user')),
            ],
        ),
    ]
